### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by iqbalridha** [vbohush/OpenCamera#1]
This is the logo proposal, i submitted for your application, sir. Tell me how you think sir. Thank you.
https://steemit.com/utopian-io/@iqbalridha/logo-design-proposal-for-open-camera-app

**Comment by vbohush** [comment]
Sorry, but this repository is just a clone. I'm not the author. Write here https://sourceforge.net/p/opencamera/code/ci/master/tree/

**Comment by iqbalridha** [comment]
Thank you for the notification, vbohush
